<?php

namespace Database\Seeders;

use App\Enums\ContractDurationEnum;
use App\Enums\TpcPayloadRangeEnum;
use App\Models\TpcPricingGrid;
use Illuminate\Database\Seeder;

class TpcPricingGridSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pricing = [
            ContractDurationEnum::ONE_MONTH->value => [
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 11897,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 2094,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 238,
                    'base_amount' => 17774,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 15519,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 2619,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 310,
                    'base_amount' => 21993,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 18972,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 3120,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 379,
                    'base_amount' => 26016,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 24462,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 3916,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 489,
                    'base_amount' => 32412,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 26093,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 4152,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 522,
                    'base_amount' => 34312,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 28000,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 4450,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 560,
                    'base_amount' => 36555,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_OVER_15->value,
                    'rc_amount' => 30000,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 750,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 4770,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 600,
                    'base_amount' => 38915,
                ],
            ],
            ContractDurationEnum::THREE_MONTHS->value => [
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 33310,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 5892,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 666,
                    'base_amount' => 48194,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 43453,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 7363,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 869,
                    'base_amount' => 60011,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 53120,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 8765,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1062,
                    'base_amount' => 71273,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 68493,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 10994,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1370,
                    'base_amount' => 89183,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 73059,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 11656,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1461,
                    'base_amount' => 94502,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 78400,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 12465,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1568,
                    'base_amount' => 100759,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_OVER_15->value,
                    'rc_amount' => 84000,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 2100,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 13338,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1680,
                    'base_amount' => 107344,
                ],
            ],
            ContractDurationEnum::SIX_MONTHS->value => [
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 63051,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 11055,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1261,
                    'base_amount' => 89556,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 82251,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 13839,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1645,
                    'base_amount' => 111924,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 100549,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 16492,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2011,
                    'base_amount' => 133241,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 129647,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 20711,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2593,
                    'base_amount' => 167140,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 138290,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 21964,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2766,
                    'base_amount' => 177209,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 148200,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 23500,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2964,
                    'base_amount' => 189853,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_OVER_15->value,
                    'rc_amount' => 158800,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 3975,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 25150,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 3176,
                    'base_amount' => 203305,
                ],
            ],
            ContractDurationEnum::TWELVE_MONTHS->value => [
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 118965,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 20505,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2379,
                    'base_amount' => 165299,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 155190,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 25758,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 3104,
                    'base_amount' => 207502,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 189715,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 30764,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 3794,
                    'base_amount' => 247723,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 244617,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 38725,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 4892,
                    'base_amount' => 311684,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 260925,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 41089,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 5219,
                    'base_amount' => 330683,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 279600,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 44000,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 5592,
                    'base_amount' => 354642,
                ],
                [
                    'payload_range' => TpcPayloadRangeEnum::RANGE_OVER_15->value,
                    'rc_amount' => 299600,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 7500,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 47100,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 5992,
                    'base_amount' => 380142,
                ],
            ],
        ];

        foreach ($pricing as $duration => $payloadRanges) {
            foreach ($payloadRanges as $row) {
                TpcPricingGrid::updateOrCreate(
                    [
                        'duration' => $duration,
                        'payload_range' => $row['payload_range'],
                    ],
                    [
                        'base_amount' => $row['base_amount'],
                        'rc_amount' => $row['rc_amount'],
                        'defence_appeal_amount' => $row['defence_appeal_amount'],
                        'person_transport_amount' => $row['person_transport_amount'],
                        'accessory_amount' => $row['accessory_amount'],
                        'taxes_amount' => $row['taxes_amount'],
                        'cedeao_amount' => $row['cedeao_amount'],
                        'fga_amount' => $row['fga_amount'],
                        'is_active' => true,
                    ]
                );
            }
        }

        $this->command->info('Grille tarifaire TPC créée avec succès !');
    }
}
