<?php

namespace Database\Seeders;

use App\Enums\ContractDurationEnum;
use App\Enums\TpmPayloadRangeEnum;
use App\Models\TpmPricingGrid;
use Illuminate\Database\Seeder;

class TpmPricingGridSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pricing = [
            ContractDurationEnum::ONE_MONTH->value => [
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 13350,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 2196,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 267,
                    'base_amount' => 18608,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 17130,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 2744,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 343,
                    'base_amount' => 23012,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 21500,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 3378,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 430,
                    'base_amount' => 28103,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 26970,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 4171,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 539,
                    'base_amount' => 34475,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 33940,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 5182,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 679,
                    'base_amount' => 42596,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 44450,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 6706,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 889,
                    'base_amount' => 54840,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_15_PLUS->value,
                    'rc_amount' => 48900,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 1000,
                    'taxes_amount' => 7351,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 978,
                    'base_amount' => 60024,
                ],
            ],
            ContractDurationEnum::THREE_MONTHS->value => [
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 37380,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 6178,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 748,
                    'base_amount' => 50532,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 47964,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 7713,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 959,
                    'base_amount' => 62862,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 60200,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 9487,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1204,
                    'base_amount' => 77117,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 75516,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 11708,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1510,
                    'base_amount' => 94960,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 95032,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 14537,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1901,
                    'base_amount' => 117696,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 124460,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 18804,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2489,
                    'base_amount' => 151979,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_15_PLUS->value,
                    'rc_amount' => 136929,
                    'defence_appeal_amount' => 2226,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 3000,
                    'taxes_amount' => 20611,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2738,
                    'base_amount' => 166495,
                ],
            ],
            ContractDurationEnum::SIX_MONTHS->value => [
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 70755,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 11595,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1415,
                    'base_amount' => 93979,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 90789,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 14500,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 1816,
                    'base_amount' => 117319,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 113950,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 17859,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2279,
                    'base_amount' => 144302,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 142941,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 22062,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2859,
                    'base_amount' => 178076,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 179882,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 27419,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 3598,
                    'base_amount' => 221113,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 235585,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 35496,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 4712,
                    'base_amount' => 286007,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_15_PLUS->value,
                    'rc_amount' => 259170,
                    'defence_appeal_amount' => 4214,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 5000,
                    'taxes_amount' => 38916,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 5183,
                    'base_amount' => 313483,
                ],
            ],
            ContractDurationEnum::TWELVE_MONTHS->value => [
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_INFERIOR_OR_EQUAL_TO_1->value,
                    'rc_amount' => 133500,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 21525,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 2670,
                    'base_amount' => 173645,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_1_3->value,
                    'rc_amount' => 171300,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 27006,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 3426,
                    'base_amount' => 217682,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_3_5->value,
                    'rc_amount' => 215000,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 33343,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 4300,
                    'base_amount' => 268593,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_5_8->value,
                    'rc_amount' => 269700,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 41274,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 5394,
                    'base_amount' => 332318,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_9_12->value,
                    'rc_amount' => 339400,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 51381,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 6788,
                    'base_amount' => 413519,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_12_15->value,
                    'rc_amount' => 444500,
                    'defence_appeal_amount' => 795,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 66620,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 8890,
                    'base_amount' => 535960,
                ],
                [
                    'payload_range' => TpmPayloadRangeEnum::RANGE_15_PLUS->value,
                    'rc_amount' => 489000,
                    'defence_appeal_amount' => 7950,
                    'person_transport_amount' => 0,
                    'accessory_amount' => 7000,
                    'taxes_amount' => 73073,
                    'cedeao_amount' => 1000,
                    'fga_amount' => 9780,
                    'base_amount' => 587803,
                ],
            ],
        ];

        foreach ($pricing as $duration => $payloadRanges) {
            foreach ($payloadRanges as $row) {
                TpmPricingGrid::updateOrCreate(
                    [
                        'duration' => $duration,
                        'payload_range' => $row['payload_range'],
                    ],
                    [
                        'base_amount' => $row['base_amount'],
                        'rc_amount' => $row['rc_amount'],
                        'defence_appeal_amount' => $row['defence_appeal_amount'],
                        'person_transport_amount' => $row['person_transport_amount'],
                        'accessory_amount' => $row['accessory_amount'],
                        'taxes_amount' => $row['taxes_amount'],
                        'cedeao_amount' => $row['cedeao_amount'],
                        'fga_amount' => $row['fga_amount'],
                        'is_active' => true,
                    ]
                );
            }
        }

        $this->command->info('Grille tarifaire TPM créée avec succès !');
    }
}
