/**
 * Helper route(name, ...params) pour générer les URLs sans dépendre de Ziggy.
 * Utiliser : import { route } from '@/route';
 */
export function route(name, ...params) {
    const routes = {
        'clients.index': () => '/clients',
        'clients.create': () => '/clients/create',
        'clients.store': () => '/clients',
        'clients.show': (id) => `/clients/${id}`,
        'clients.edit': (id) => `/clients/${id}/edit`,
        'clients.update': (id) => `/clients/${id}`,
        'clients.destroy': (id) => `/clients/${id}`,
        'vehicles.index': () => '/vehicles',
        'vehicles.create': () => '/vehicles/create',
        'vehicles.create.for_client': (clientId) => `/clients/${clientId}/vehicles/create`,
        'vehicles.store': () => '/vehicles',
        'vehicles.show': (id) => `/vehicles/${id}`,
        'vehicles.edit': (id) => `/vehicles/${id}/edit`,
        'vehicles.update': (id) => `/vehicles/${id}`,
        'vehicles.destroy': (id) => `/vehicles/${id}`,
        'contracts.index': () => '/contracts',
        'contracts.create': () => '/contracts/create',
        'contracts.preview': () => '/contracts/preview',
        'contracts.store': () => '/contracts',
        'contracts.show': (id) => `/contracts/${id}`,
        'contracts.pdf': (id) => `/contracts/${id}/pdf`,
        'contracts.edit': (id) => `/contracts/${id}/edit`,
        'contracts.update': (id) => `/contracts/${id}`,
        'contracts.cancel': (id) => `/contracts/${id}/cancel`,
        'contracts.mark-attestation-issued': (id) => `/contracts/${id}/mark-attestation-issued`,
        'contracts.generate-attestation': (id) => `/contracts/${id}/generate-attestation`,
        'contracts.destroy': (id) => `/contracts/${id}`,
        'referential.brands.index': () => '/referential/brands',
        'referential.brands.create': () => '/referential/brands/create',
        'referential.brands.store': () => '/referential/brands',
        'referential.brands.edit': (id) => `/referential/brands/${id}/edit`,
        'referential.brands.update': (id) => `/referential/brands/${id}`,
        'referential.brands.destroy': (id) => `/referential/brands/${id}`,
        'referential.models.index': () => '/referential/models',
        'referential.models.create': () => '/referential/models/create',
        'referential.models.store': () => '/referential/models',
        'referential.models.edit': (id) => `/referential/models/${id}/edit`,
        'referential.models.update': (id) => `/referential/models/${id}`,
        'referential.models.destroy': (id) => `/referential/models/${id}`,
        'digital.attestations': () => '/digital/attestations',
        'digital.attestations.download': (ref) => `/digital/attestations/${ref}/download`,
        'digital.rattachements': () => '/digital/rattachements',
        'digital.stock': () => '/digital/stock',
        'digital.stock.create': () => '/digital/stock/create',
        'digital.transactions.store': () => '/digital/transactions',
        'digital.transactions.cancel': (ref) => `/digital/transactions/${ref}/cancel`,
        'digital.utilisateurs': () => '/digital/utilisateurs',
        'digital.utilisateurs.create': () => '/digital/utilisateurs/create',
        'digital.utilisateurs.store': () => '/digital/utilisateurs',
        'digital.utilisateurs.edit': (id) => `/digital/utilisateurs/${id}/edit`,
        'digital.utilisateurs.update': (id) => `/digital/utilisateurs/${id}`,
        'digital.utilisateurs.enable': (id) => `/digital/utilisateurs/${id}/enable`,
        'digital.utilisateurs.disable': (id) => `/digital/utilisateurs/${id}/disable`,
        'digital.bureaux': () => '/digital/bureaux',
        'digital.bureaux.create': () => '/digital/bureaux/create',
        'digital.bureaux.store': () => '/digital/bureaux',
        'digital.bureaux.edit': (id) => `/digital/bureaux/${id}/edit`,
        'digital.bureaux.update': (id) => `/digital/bureaux/${id}`,
        'digital.bureaux.enable': (id) => `/digital/bureaux/${id}/enable`,
        'digital.bureaux.disable': (id) => `/digital/bureaux/${id}/disable`,
    };
    const fn = routes[name];
    if (!fn) return '#';
    return fn(...params);
}
